/**
 * Standardized error codes for the application
 * Format: DOMAIN_ERROR_TYPE
 */
export enum ErrorCode {
  // Authentication & Authorization (AUTH_*)
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_USER_ALREADY_EXISTS = 'AUTH_USER_ALREADY_EXISTS',
  AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',

  // Resource Not Found (RESOURCE_*)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_RESTAURANT_NOT_FOUND = 'RESOURCE_RESTAURANT_NOT_FOUND',
  RESOURCE_USER_NOT_FOUND = 'RESOURCE_USER_NOT_FOUND',
  RESOURCE_MENU_ITEM_NOT_FOUND = 'RESOURCE_MENU_ITEM_NOT_FOUND',
  RESOURCE_REBUILD_NOT_FOUND = 'RESOURCE_REBUILD_NOT_FOUND',
  RESOURCE_DEPLOYMENT_NOT_FOUND = 'RESOURCE_DEPLOYMENT_NOT_FOUND',
  RESOURCE_WORDPRESS_SITE_NOT_FOUND = 'RESOURCE_WORDPRESS_SITE_NOT_FOUND',

  // Validation Errors (VALIDATION_*)
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_INVALID_URL = 'VALIDATION_INVALID_URL',
  VALIDATION_INVALID_EMAIL = 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PHONE = 'VALIDATION_INVALID_PHONE',
  VALIDATION_MISSING_REQUIRED_FIELD = 'VALIDATION_MISSING_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',

  // Scraper Errors (SCRAPER_*)
  SCRAPER_FAILED = 'SCRAPER_FAILED',
  SCRAPER_TIMEOUT = 'SCRAPER_TIMEOUT',
  SCRAPER_INVALID_URL = 'SCRAPER_INVALID_URL',
  SCRAPER_ACCESS_DENIED = 'SCRAPER_ACCESS_DENIED',
  SCRAPER_RATE_LIMITED = 'SCRAPER_RATE_LIMITED',

  // WordPress Errors (WP_*)
  WP_CONNECTION_FAILED = 'WP_CONNECTION_FAILED',
  WP_AUTHENTICATION_FAILED = 'WP_AUTHENTICATION_FAILED',
  WP_DEPLOYMENT_FAILED = 'WP_DEPLOYMENT_FAILED',
  WP_INVALID_CREDENTIALS = 'WP_INVALID_CREDENTIALS',
  WP_API_ERROR = 'WP_API_ERROR',
  WP_SITE_UNREACHABLE = 'WP_SITE_UNREACHABLE',

  // AI/LLM Errors (AI_*)
  AI_SERVICE_UNAVAILABLE = 'AI_SERVICE_UNAVAILABLE',
  AI_QUOTA_EXCEEDED = 'AI_QUOTA_EXCEEDED',
  AI_INVALID_RESPONSE = 'AI_INVALID_RESPONSE',
  AI_TIMEOUT = 'AI_TIMEOUT',
  AI_RATE_LIMITED = 'AI_RATE_LIMITED',

  // Database Errors (DB_*)
  DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED',
  DB_QUERY_FAILED = 'DB_QUERY_FAILED',
  DB_TRANSACTION_FAILED = 'DB_TRANSACTION_FAILED',
  DB_CONSTRAINT_VIOLATION = 'DB_CONSTRAINT_VIOLATION',
  DB_UNIQUE_VIOLATION = 'DB_UNIQUE_VIOLATION',

  // Queue/Job Errors (QUEUE_*)
  QUEUE_JOB_FAILED = 'QUEUE_JOB_FAILED',
  QUEUE_CONNECTION_FAILED = 'QUEUE_CONNECTION_FAILED',
  QUEUE_TIMEOUT = 'QUEUE_TIMEOUT',

  // File/Media Errors (MEDIA_*)
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  MEDIA_FILE_TOO_LARGE = 'MEDIA_FILE_TOO_LARGE',
  MEDIA_INVALID_TYPE = 'MEDIA_INVALID_TYPE',
  MEDIA_STORAGE_FULL = 'MEDIA_STORAGE_FULL',

  // Rate Limiting (RATE_LIMIT_*)
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_TOO_MANY_REQUESTS = 'RATE_LIMIT_TOO_MANY_REQUESTS',

  // Business Logic Errors (BIZ_*)
  BIZ_INVALID_OPERATION = 'BIZ_INVALID_OPERATION',
  BIZ_DUPLICATE_ENTRY = 'BIZ_DUPLICATE_ENTRY',
  BIZ_INSUFFICIENT_CREDITS = 'BIZ_INSUFFICIENT_CREDITS',
  BIZ_FEATURE_NOT_AVAILABLE = 'BIZ_FEATURE_NOT_AVAILABLE',

  // System/Internal Errors (SYS_*)
  SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
  SYS_SERVICE_UNAVAILABLE = 'SYS_SERVICE_UNAVAILABLE',
  SYS_MAINTENANCE = 'SYS_MAINTENANCE',
  SYS_CONFIGURATION_ERROR = 'SYS_CONFIGURATION_ERROR',

  // Network Errors (NET_*)
  NET_TIMEOUT = 'NET_TIMEOUT',
  NET_CONNECTION_REFUSED = 'NET_CONNECTION_REFUSED',
  NET_DNS_FAILED = 'NET_DNS_FAILED',

  // Unknown/Generic
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

/**
 * Error code to HTTP status code mapping
 */
export const ErrorCodeToHttpStatus: Record<ErrorCode, number> = {
  // 401 Unauthorized
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_UNAUTHORIZED]: 401,
  [ErrorCode.WP_AUTHENTICATION_FAILED]: 401,
  [ErrorCode.WP_INVALID_CREDENTIALS]: 401,

  // 403 Forbidden
  [ErrorCode.AUTH_FORBIDDEN]: 403,
  [ErrorCode.SCRAPER_ACCESS_DENIED]: 403,

  // 404 Not Found
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_RESTAURANT_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_USER_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_MENU_ITEM_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_REBUILD_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_DEPLOYMENT_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_WORDPRESS_SITE_NOT_FOUND]: 404,
  [ErrorCode.AUTH_USER_NOT_FOUND]: 404,

  // 409 Conflict
  [ErrorCode.AUTH_USER_ALREADY_EXISTS]: 409,
  [ErrorCode.BIZ_DUPLICATE_ENTRY]: 409,
  [ErrorCode.DB_UNIQUE_VIOLATION]: 409,

  // 422 Unprocessable Entity
  [ErrorCode.VALIDATION_FAILED]: 422,
  [ErrorCode.VALIDATION_INVALID_URL]: 422,
  [ErrorCode.VALIDATION_INVALID_EMAIL]: 422,
  [ErrorCode.VALIDATION_INVALID_PHONE]: 422,
  [ErrorCode.VALIDATION_MISSING_REQUIRED_FIELD]: 422,
  [ErrorCode.VALIDATION_INVALID_FORMAT]: 422,
  [ErrorCode.AUTH_WEAK_PASSWORD]: 422,
  [ErrorCode.SCRAPER_INVALID_URL]: 422,
  [ErrorCode.BIZ_INVALID_OPERATION]: 422,

  // 413 Payload Too Large
  [ErrorCode.MEDIA_FILE_TOO_LARGE]: 413,

  // 415 Unsupported Media Type
  [ErrorCode.MEDIA_INVALID_TYPE]: 415,

  // 429 Too Many Requests
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.RATE_LIMIT_TOO_MANY_REQUESTS]: 429,
  [ErrorCode.SCRAPER_RATE_LIMITED]: 429,
  [ErrorCode.AI_RATE_LIMITED]: 429,

  // 500 Internal Server Error
  [ErrorCode.SYS_INTERNAL_ERROR]: 500,
  [ErrorCode.DB_QUERY_FAILED]: 500,
  [ErrorCode.DB_TRANSACTION_FAILED]: 500,
  [ErrorCode.DB_CONSTRAINT_VIOLATION]: 500,
  [ErrorCode.QUEUE_JOB_FAILED]: 500,
  [ErrorCode.MEDIA_UPLOAD_FAILED]: 500,
  [ErrorCode.UNKNOWN_ERROR]: 500,
  [ErrorCode.SYS_CONFIGURATION_ERROR]: 500,

  // 502 Bad Gateway
  [ErrorCode.WP_CONNECTION_FAILED]: 502,
  [ErrorCode.WP_SITE_UNREACHABLE]: 502,
  [ErrorCode.AI_SERVICE_UNAVAILABLE]: 502,
  [ErrorCode.NET_CONNECTION_REFUSED]: 502,
  [ErrorCode.NET_DNS_FAILED]: 502,

  // 503 Service Unavailable
  [ErrorCode.SYS_SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.SYS_MAINTENANCE]: 503,
  [ErrorCode.DB_CONNECTION_FAILED]: 503,
  [ErrorCode.QUEUE_CONNECTION_FAILED]: 503,
  [ErrorCode.MEDIA_STORAGE_FULL]: 503,

  // 504 Gateway Timeout
  [ErrorCode.NET_TIMEOUT]: 504,
  [ErrorCode.SCRAPER_TIMEOUT]: 504,
  [ErrorCode.AI_TIMEOUT]: 504,
  [ErrorCode.QUEUE_TIMEOUT]: 504,

  // 507 Insufficient Storage
  [ErrorCode.BIZ_INSUFFICIENT_CREDITS]: 402,

  // 501 Not Implemented
  [ErrorCode.BIZ_FEATURE_NOT_AVAILABLE]: 501,

  // AI specific errors
  [ErrorCode.AI_QUOTA_EXCEEDED]: 429,
  [ErrorCode.AI_INVALID_RESPONSE]: 500,

  // WordPress specific
  [ErrorCode.WP_DEPLOYMENT_FAILED]: 500,
  [ErrorCode.WP_API_ERROR]: 502,

  // Scraper specific
  [ErrorCode.SCRAPER_FAILED]: 500,
};
